### ISSUE TITLE
latex-build with -shell-escape option

### ISSUE THREAD

**Issue by qcfu-bu** [sublimelsp/LSP-TexLab#14]
To use the minted latex package for syntax highlight code snippets, a build option "-shell-escape" needs to be enabled. Despite enabling it and being able to build the pdf, latex-build still produces an error message saying that it should be enabled.

**Comment by LDAP** [comment]
Since the build is completely independent of this plugin and the TexLab server, this is most likely an issue with your build command. Can you provide your LSP-TexLab settings?

**Comment by qcfu-bu** [comment]
I think this is just due to me mis-configuring the settings. Everything seems to be working after I copied the entire Tex-lsp settings template and modified just the texlab.build.args entry.
