### ISSUE TITLE
zip downloading fails during installation

### ISSUE THREAD

**Issue by UGL1** [sublimelsp/LSP-TexLab#18]
Win10, SublimeText portable edition build 4143.
No other LaTeX related packages installed.
During installation, plugin is downloading a file. It fails : "not a gzip file".

**Comment by LDAP** [comment]
Could not replicate here.
Is there an error in the Sublime Text console?

**Comment by UGL1** [comment]
![image](https://github.com/sublimelsp/LSP-TexLab/assets/107758164/2b50d9d4-48ca-437f-b49e-933e33db6335)
This is the only thing I see after the download.

**Comment by jfcherng** [comment]
That looks like https://github.com/sublimelsp/LSP-ltex-ls rather than this.

**Comment by UGL1** [comment]
omg, i'm sorry.

**Comment by jfcherng** [comment]
Closed as invalid.
