### ISSUE TITLE
cannot clean temporary files?

### ISSUE THREAD

**Issue by islercn** [sublimelsp/LSP-TexLab#3]
i use sublime 4 + texlab 3.0.1, there will be too many .fls files after build

if i add "-c" to texlab.build.args, i always get:

LSP-TexLab: Latexmk: Cannot remove file 'xxx.log'
LSP-TexLab: Latexmk: Cannot remove file 'xxx.fls'
LSP-TexLab: Latexmk: Cannot remove file 'xxx.aux'

(no such problem for sublime3 + latextools)

**Comment by LDAP** [comment]
LSP-TexLab is only a bridge to https://github.com/latex-lsp/texlab. As this is a TexLab issue, you should open the issue there.
