### ISSUE TITLE
specify pdf viewer for compilation via LSP

### ISSUE THREAD

**Issue by islercn** [sublimelsp/LSP-TexLab#6]
to use SumatraPDF as the PDF previewer, i have to create and modify %USERPROFILE%/.latexmkrc

i don't know if it can be set in LSP-TexLab, so that i can make sublime become more portable

**Comment by jfcherng** [comment]
Potentially by https://github.com/sublimelsp/LSP-TexLab/blob/78bbb316aa16768f3addda2e409fa53df8f006e5/LSP-TexLab.sublime-settings#L30. Probably `$packages` can be used in that but I am not sure. Wondering what you comfort you the best?

**Comment by islercn** [comment]
> Potentially by
> 
> https://github.com/sublimelsp/LSP-TexLab/blob/78bbb316aa16768f3addda2e409fa53df8f006e5/LSP-TexLab.sublime-settings#L30
> 
> . Probably `$packages` can be used in that but I am not sure. Wondering what you comfort you the best?

maybe the description is not correct

if i do not create .latexmkrc and add "-pvc" to texlab.build.args, the newly compiled pdf file will be opened in the default pdf viewer, like adobe acrobat, not sumatrapdf

**Comment by rwols** [comment]
Is the name of that setting correct?

https://texlab.netlify.app/docs/reference/configuration#latexforwardsearchexecutable

the website mentions `latex.forwardSearch.executable`

**Comment by LDAP** [comment]
Yes. The `latex.` prefix was changed to `texlab.` starting with version 3.

**Comment by islercn** [comment]
> Is the name of that setting correct?
> 
> https://texlab.netlify.app/docs/reference/configuration#latexforwardsearchexecutable
> 
> the website mentions `latex.forwardSearch.executable`

it is correct, but i think this option is only for forward search, not to view the pdf file after compilation

**Comment by LDAP** [comment]
> 
> 
> > Potentially by
> > https://github.com/sublimelsp/LSP-TexLab/blob/78bbb316aa16768f3addda2e409fa53df8f006e5/LSP-TexLab.sublime-settings#L30
> > 
> > . Probably `$packages` can be used in that but I am not sure. Wondering what you comfort you the best?
> 
> maybe the description is not correct, i think this option is only for forward search
> 
> if i do not create .latexmkrc but add "-pvc" to texlab.build.args, the newly compiled pdf file will be opened in the default pdf viewer, like adobe acrobat, not sumatrapdf

I think these are two different things. If you use `-pvc` latexmk starts your default PDF viewer of the viewer that was set in `latexmkrc`. The TexLab setting controls the viewer used for forward search using the TexLab command.

**Comment by islercn** [comment]
> > > Potentially by
> > > https://github.com/sublimelsp/LSP-TexLab/blob/78bbb316aa16768f3addda2e409fa53df8f006e5/LSP-TexLab.sublime-settings#L30
> > > 
> > > . Probably `$packages` can be used in that but I am not sure. Wondering what you comfort you the best?
> > 
> > 
> > maybe the description is not correct, i think this option is only for forward search
> > if i do not create .latexmkrc but add "-pvc" to texlab.build.args, the newly compiled pdf file will be opened in the default pdf viewer, like adobe acrobat, not sumatrapdf
> 
> I think these are two different things. If you use `-pvc` latexmk starts your default PDF viewer of the viewer that was set in `latexmkrc`. The TexLab setting controls the viewer used for forward search using the TexLab command.

yeap, it is not a bug, i only  hope it can be controlled in LSP-TexLab, like latextools

**Comment by islercn** [comment]
https://github.com/latex-lsp/texlab/issues/436
