### ISSUE TITLE
Is auto-completion supported ?

### ISSUE THREAD

**Issue by JPenuchot** [sublimelsp/LSP-TexLab#7]
Hello,

Is auto-completion supposed to work? I'm running LSP-TexLab on Sublime 4113, I get documentation popups when hovering things like bibtex citations, build on save also works, but auto-completion doesn't work as it does in the Texlab demo:

![](https://github.com/latex-lsp/texlab/raw/master/docs/demo.gif)

Tried my best reading LSP-Texlab and Texlab's documentations, hopefully I didn't miss anything too obvious.

Regards,
Jules

**Comment by jfcherng** [comment]
@JPenuchot FYI, https://github.com/sublimelsp/LSP-TexLab/issues/9#issuecomment-914072841

You would have to add `text.tex` into `auto_complete_selector` in ST's settings.

```js
"auto_complete_selector": "meta.tag, (source | text.tex) - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc",
```

**Comment by jfcherng** [comment]
FYI, in the latest LSP-TexLab 0.4.4, the autocompletion should be auto working more like VSCode. Thanks to @rwols
